### ISSUE TITLE
Unquoted $@ breaks with globs

### ISSUE THREAD

**Issue by Artoria2e5** [ilikenwf/apt-fast#101]
`apt-get install` accepts globs or regexes in the form of `apt-get install 'a*'`. These forms overlap with some shell glob metachars, and the argument parsing `for arguments in $@` in `apt-fast` just happily expends it for the current workdir. Using `"$@"` solves this problem.

PS. The if statements in the matching look a bit too heavy to me. Perhaps it's more appropriate to do the matching in a `case` statement?

PPS. The `mirrors=( ${mirrorstr//,/ } )` thing can be improved in plain-bash with `mirrors=( ${mirrorstr//*([[:space:]]),*([[:space:]])/ } )`. This requires `shopt -s extglob` (available in bash 3.0+).

**Comment by Burnfaker** [comment]
i will review this

**Comment by Artoria2e5** [comment]
Paste the whole source into shellcheck.net points out quite a few similar issues.
http://www.shellcheck.net/

The "mirrors" PPS should better be replaced with a quick little temporary `IFS+=','` -- treating the comma as a splittable character, along with spaces/tabs/newlines. Use IFS=${IFS%,} later to ditch that comma and restore the old IFS.
