### ISSUE TITLE
Warning on apt-fast.config file while reconfigure apt-fast

### ISSUE THREAD

**Issue by Dab0u1** [ilikenwf/apt-fast#102]
Hi,

Dont know if I am in the right place but...
When you run dpkg-reconfigure on apt-fast version 1.8.3~137+git7b72bb7-0ubuntu1~ppa3  (on willy and xenial) wich is on https://launchpad.net/~saiarcot895 ppa you have this warning at the end of the reconfiguring: 
<code> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /var/lib/dpkg/info/apt-fast.config line 205." </code>
The original line is: 
<code> if ($downloadcmd =~ /\${_MAXNUM}/){  </code>
But it can be replaced by 
<code>if ($downloadcmd =~ /\${_MAXNUM}/){ </code> and the regex warning will disapear.

Edit: I'm sorry but I don't know why but the corrected code don't appear even in the brace, so I put space to see it:
<code>if ($downloadcmd =~ /\$ \ <-- HERE {_MAXNUM}/){ </code>

**Comment by Burnfaker** [comment]
hi, can you put it in the code braces?

`so here :)`

**Comment by chrstphrchvz** [comment]
I think this has to do with PPA/.deb packaging rather than the code on this repo, @saiarcot895 is who I would refer this to

**Comment by bepstein111** [comment]
So this has just always been a thing that I ignored while using apt-fast, but after trying to install today on Kubuntu 17.10, it's outright preventing me from using apt-fast at all. Maybe its more strict about illegal regex? Anyway, while attempting to fix this, I've run into multiple issues:
First, the above "solution" is incorrect for the latest version, the actual line reads:
`if ($downloadcmd =~ /\${_MAXNUM}/){`
(notice the back-to-back forward- then back- slash)
and second, upon trying the solution, dpkg complains that _MAXNUM was never declared.
It might not have to do with the code, as @chrstphrchvz said, but if it's going to break the whole app, then it's our problem.

**Comment by Lasall** [comment]
Thank you for reporting this issue and providing a fix. I updated the apt-fast/stable PPA with the current version and fixed this issue in the config file.
