### ISSUE TITLE
max-connection-per-server the Possible Values: 1-16

### ISSUE THREAD

**Issue by udiNur** [ilikenwf/apt-fast#104]
the possible values: 1-16, but in the install dialog message this limit not shows, and i can set more then 16, and then the "apt-fast" command shows this msg, and start apt-get 

Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--max-connection-per-server'.
  -> [OptionHandlerImpl.cc:187] errorCode=1 max-connection-per-server must be between 1 and 16.
Usage:
 -x, --max-connection-per-server=NUM The maximum number of connections to one
                              server for each download.

```
                          Possible Values: 1-16
                          Default: 1
                          Tags: #basic, #http, #ftp
```

**Comment by thebali** [comment]
Me having same issue. I tried removing `apt-fast` and then reinstalling. It didn't work.

**Comment by thebali** [comment]
`sudo nano /etc/apt-fast.conf` then scroll down to find `_MAXNUM=25` to `_MAXNUM=15`.
Select `_MAXNUM` between 1-16.

Found solution [here](https://askubuntu.com/questions/583695/apt-fast-upgrade-not-working-in-ubuntu-14-04)

**Comment by ahsanhussain** [comment]
You can also reconfigure the package:

$ sudo dpkg-reconfigure apt-fast

**Comment by udiNur** [comment]
I know how to fix it.. 
But is not user friendly to allow the user to enter number that more then the maximum..

**Comment by Lasall** [comment]
apt-fast 1.8.5-1 on the apt-fast/stable PPA should fix this issue. Please reopen if it still persists. Thank you for reporting and helping with workarounds!
