### ISSUE TITLE
Does apt-fast make use of apt-transport-tor?

### ISSUE THREAD

**Issue by 1geeky** [ilikenwf/apt-fast#109]
Does **apt-fast** transmit the whole traffic through Tor network via [apt-transport-tor](https://github.com/diocles/apt-transport-tor)?
If so, does it require any extra work on the `.conf` file?

Thanks

**Comment by Lasall** [comment]
There is no socks proxy support in aria2c. Check https://github.com/aria2/aria2/issues/153 for more information.

**Comment by NexusSfan** [comment]
@Lasall See aria2/aria2#1231 for the solution.
