### ISSUE TITLE
error checksum

### ISSUE THREAD

**Issue by riloraspopo** [ilikenwf/apt-fast#110]
12/19 10:13:32 [ERROR] Checksum error detected. file=/var/cache/apt/archives/apt-fast/grep_2.27-1_amd64.deb

12/19 10:13:32 [NOTICE] Download GID#9d1bfdafc63dda12 not complete: /var/cache/apt/archives/apt-fast/grep_2.27-1_amd64.deb

12/19 10:13:32 [ERROR] Checksum error detected. file=/var/cache/apt/archives/apt-fast/perl_5.24.1~rc4-1_amd64.deb

12/19 10:13:32 [NOTICE] Download GID#2480c01c06ae4816 not complete: /var/cache/apt/archives/apt-fast/perl_5.24.1~rc4-1_amd64.deb

12/19 10:13:32 [ERROR] Checksum error detected. file=/var/cache/apt/archives/apt-fast/login_1%3a4.2-3.3_amd64.deb

12/19 10:13:32 [NOTICE] Download GID#59f44d0d806c7b4d not complete: /var/cache/apt/archives/apt-fast/login_1%3a4.2-3.3_amd64.deb

just regural syntax, apt-fast upgrade

**Comment by chrstphrchvz** [comment]
probably too late but I would suggest `apt-fast clean` and try again

**Comment by sonvirgo** [comment]
same

**Comment by Lasall** [comment]
@sonvirgo Do you get a similar error?

**Comment by sonvirgo** [comment]
@Lasall yeah, I have exact same error. Kali linux

**Comment by Lasall** [comment]
Did you try `apt-fast clean` ?

**Comment by sonvirgo** [comment]
Yeah

**Comment by Lasall** [comment]
Are you behind a proxy?

**Comment by sonvirgo** [comment]
Absolute not. I afraid this is kali issue, ubuntu repo run fine

**Comment by riloraspopo** [comment]
actually, this may be because you did not complete the whole process while installing (manual install in ubuntu friendches)... 

n for kali linux, I have not figured out why this happened...

**Comment by Lasall** [comment]
What is the output of `apt-get download --print-uris PACKAGE` for one package that fails to verify?

**Comment by sonvirgo** [comment]
Generally apt-fast work just fine. But some times it claim that /var/lock is on hold or some thing.
So I have to use apt.
Even some time apt report rogue error.
Finally use aptitude to get the correct probrem

**Comment by Feliz-S** [comment]
It can be solved by changing the default downloader from aria2 to axel?
because aria2 checks File integrity.If you know how to change please write a comment?
cause I've tried but it's not that efficient and the downloads are failing 
Step1: I've downloaded a (.deb) file from Ubuntu ppa and installed it.
Step2: Run dpkg-reconfigure apt-fast
step3- after choosing it's asking to choose to choose a default downloader Select custom and added 
 

cat "${DLLIST}" | xargs -l1 axel -n "${_MAXNUM}" -a	
it does the work but not that stable.

credits:
http://forum.top-hat-sec.com/index.php?topic=3482.0

**Comment by Lasall** [comment]
The DLLIST file has a special format for aria2. So it might need some
processing first. I will look into it later. The axel support was dropped
because because of some limitations at that time
https://askubuntu.com/a/291171

**Comment by moham96** [comment]
This is the same problem as in #114  the problem is that some server (kali linux and raspbian) send a `.meta4` file ([metalink](https://en.wikipedia.org/wiki/Metalink)) which contains geolocation based mirrors for the file, I think the problem is that aria2 downloads both the `.meta4` and the `.deb` file but later when apt tests the checksum it checks it against the `.meta4` file and not against the `.deb` file which causes the checksum to fail
the workaround I mentioned in #114 works  because with that header added aria2 will only download the `.deb` file.
There is probably a better solution in aria2 but I didn't dig deeper
```
root@kali:~# curl -v http://http.kali.org/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb
*   Trying 192.99.200.113...
* TCP_NODELAY set
* Connected to http.kali.org (192.99.200.113) port 80 (#0)
> GET /kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb HTTP/1.1
> Host: http.kali.org
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Wed, 24 Oct 2018 23:32:36 GMT
< Server: Apache/2.4.10 (Debian)
< X-MirrorBrain-Mirror: kali.download
< X-MirrorBrain-Realm: other_country
< Link: <http://http.kali.org/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb.meta4>; rel=describedby; type="application/metalink4+xml"
< Link: <http://kali.download/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb>; rel=duplicate; pri=1; geo=us
< Link: <http://mirror.karneval.cz/pub/linux/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb>; rel=duplicate; pri=2; geo=cz
< Link: <http://ftp.acc.umu.se/mirror/kali.org/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb>; rel=duplicate; pri=3; geo=se
< Link: <http://mirrors.dotsrc.org/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb>; rel=duplicate; pri=4; geo=dk
< Link: <http://ftp.belnet.be/pub/kali/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb>; rel=duplicate; pri=5; geo=be
< Location: http://kali.download/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 328
< Connection: Keep-Alive
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://kali.download/kali/pool/main/o/openssh/ssh_7.8p1-1_all.deb">here</a>.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at http.kali.org Port 80</address>
</body></html>
* Connection #0 to host http.kali.org left intact
```

**Comment by PhDEngendro** [comment]
i can solved just changing the download directory to tmp...

**Comment by PhDEngendro** [comment]
> i can solved just changing the download directory to tmp...

dpkg-reconfigure apt-fast and then change the download and cache directory... i put "/tmp/apt-fast' and "/tmp/apt-fast/cache"

**Comment by Lasall** [comment]
This bug report mixes several different issues. Metalink related problems are discussed in #114. For new checksum problems please open a new issue.

**Comment by denaturedBatToken** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who is protecting his bully budies in the hate group Storm Ryders. You will receive these messages until I stop being bullies by @Lasall and his buddies or a better way to achieve that is made available.
