### ISSUE TITLE
Warning while Installing on Xenial Xerus

### ISSUE THREAD

**Issue by C-F-4** [ilikenwf/apt-fast#111]
I got this warning while installing apt-fast package on Ubuntu 16.04 LTS Release.

`
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /var/lib/dpkg/info/apt-fast.config line 212.
`

**Comment by chrstphrchvz** [comment]
duplicate of #102 ?

**Comment by Lasall** [comment]
Duplicate of #102
