### ISSUE TITLE
checksums error when downloading on a raspberry pi

### ISSUE THREAD

**Issue by moham96** [ilikenwf/apt-fast#114]
apt-fast is giving checksum errors, this is because raspberry pi servers(http://mirrordirector.raspbian.org) sends a metalink with mirrors and then aria2 checks the md5 hash in /tmp/apt-fast.list against this metalink file and throws an error

**Comment by moham96** [comment]
a quick and dirty workaround is to add ` --header "Accept: */*"` to aria2 command line which prevent aria from downloading metalink file

**Comment by war59312** [comment]
Fix any time soon?

**Comment by robertoaceves** [comment]
A little less intrusive option is to add the next line to the `/etc/apt-fast.conf` file:
`_DOWNLOADER="${_DOWNLOADER} --header 'Accept: */*'"`

**Comment by Lasall** [comment]
I added this fix to the FAQ section in the Readme.

**Comment by Lasall** [comment]
Actually since this is not only raspberry related I added this to the default command line.
