### ISSUE TITLE
apt- fast not downloading behind proxy 

### ISSUE THREAD

**Issue by hemkum** [ilikenwf/apt-fast#115]
added ppa using using -E, but still apt-fast not downloading behind proxy , apt-get is working properly

**Comment by Lasall** [comment]
Thank you for reporting this issue. Did you configure the proxy settings in /etc/apt-fast.conf ?

**Comment by Lasall** [comment]
For anyone looking into this issue: We should probably support environment variable http_proxy and also make sure we use apt's Acquire::http::Proxy. A quick google check led me [there](https://askubuntu.com/questions/7470/how-to-run-sudo-apt-get-update-through-proxy-in-commandline).
