### ISSUE TITLE
Can't install in Ubuntu 17.04. Repository missing release file error. (Workaround available)

### ISSUE THREAD

**Issue by mspamed** [ilikenwf/apt-fast#123]
Current workaround:

Go to Software & Updates>Other Softwares
Edit saiarcot895 entry.
Change zesty to yakkety.

Run update and install apt-fast through terminal.

**Comment by chrstphrchvz** [comment]
@saiarcot895 would you be able to add zesty to your PPA to fix this?

**Comment by saiarcot895** [comment]
Done.
