### ISSUE TITLE
It may be better to add '--no-conf' argument default

### ISSUE THREAD

**Issue by sgqy** [ilikenwf/apt-fast#126]
I have a file `~/.aria2/aria2.conf` to use `aria2c` as an RPC download server.
When I use apt-fast, it will throw errors saying port is listened.
I used `dpkg-reconfigure`, added `--no-conf` to the command, then it worked fine.

This is my current config:
```
aria2c --no-conf -c -j ${_MAXNUM} -x ${_MAXNUM} -s ${_MAXNUM} --min-split-size=1M -i ${DLLIST} --connect-timeout=600 --timeout=600 -m0
```

**Comment by Lasall** [comment]
Thank you!
