### ISSUE TITLE
add option to show package names only

### ISSUE THREAD

**Issue by chrstphrchvz** [ilikenwf/apt-fast#134]
Currently, when running apt-fast, what is displayed is the URLs to be downloaded along with their checksum and filenames, e.g.:
```

 Working... this may take a while.

# apt-fast mirror list: Thu Jan  4 08:58:29 CST 2018
http://mirror.rackspace.com/ubuntu/pool/universe/p/pcre2/libpcre2-8-0_10.22-3_i386.deb
 checksum=md5=5afe67f50bfd454201865755e38a1c1f
 out=libpcre2-8-0_10.22-3_i386.deb
http://mirror.rackspace.com/ubuntu/pool/main/a/apport/python3-problem-report_2.20.7-0ubuntu3.7_all.deb
 checksum=md5=695a689d605ccbf0cc993736180c7b67
 out=python3-problem-report_2.20.7-0ubuntu3.7_all.deb
http://mirror.rackspace.com/ubuntu/pool/main/a/apport/python3-apport_2.20.7-0ubuntu3.7_all.deb
 checksum=md5=6638f064ad7298cfcf4e6127804df923
 out=python3-apport_2.20.7-0ubuntu3.7_all.deb
[…]

 If you want to download the packages on your system press Y else n to abort. [Y/n]:

```
For a cleaner preview of which packages are to be downloaded/installed, I would suggest adding an option in apt-fast.conf that instead only prints the package names. I don't know if there's a way to get only the package names when using `--print-uris` without running apt/apt-get twice, increasing the delay; so printing just the output filenames might be sufficient:
```

 Working... this may take a while.

 libpcre2-8-0_10.22-3_i386.deb
 python3-problem-report_2.20.7-0ubuntu3.7_all.deb
 python3-apport_2.20.7-0ubuntu3.7_all.deb
[…]

 If you want to download the packages on your system press Y else n to abort. [Y/n]:
```

Of course, keeping the current output style as an option might still be useful for debugging.

**Comment by Lasall** [comment]
Thank you for coming up with this request! :)
