### ISSUE TITLE
should _APTMGR be run if --download-only is specified?

### ISSUE THREAD

**Issue by chrstphrchvz** [ilikenwf/apt-fast#136]
One possible optimization I thought of was that if `--download-only` was specified, then don't invoked the _APTMGR when apt-fast finishes downloading files.

However, given issues such as #68 where aptitude does not provide URIs but might select packages differently than apt-get, then aptitude would need to be invoked anyways to finish downloading needed files. So maybe only if _APTMGR is on the whitelist (apt-get, apt) should this optimization be applied.

**Comment by Lasall** [comment]
Good point with aptitude. Would be a nice option to have for apt-get especially if someone has a big apt cache.
