### ISSUE TITLE
Aria checksum support check fails with non-English locale

### ISSUE THREAD

**Issue by tassiovirginio** [ilikenwf/apt-fast#139]
In my distribution the aria2c help is in portuguese. Making the following line not work:
`for supported_hash in $(aria2c -v | sed '/^Hash Algorithms:/!d; s/\(^Hash Algorithms: \|,\)\+//g'); do`

I temporarily left it this way:
`aria2c -v | sed '/^Algoritmos Hash:/!d; s/\(^Algoritmos Hash: \|,\)\+//g'`

with that error the apt-fast stops running.

**Comment by Lasall** [comment]
Thank you for this report! Can you try with `LC_ALL=C aria2c -v ...`

**Comment by Lasall** [comment]
Please verify if the recent commit fixes your issue.
