### ISSUE TITLE
Aria2 download info not showing correctly [Regression]

### ISSUE THREAD

**Issue by guekho64** [ilikenwf/apt-fast#140]
Since I discovered <i>Apt-Fast</i>, I've been using it to "power up" the old faithful <i>Apt-Get</i>, but recently I started to note a weird change in <i>Apt-Fast</i> behavior, so I decided to track down the source of it.

As a result of using <i>Apt-Fast</i> almost daily, I became used to seeing the usual "Working... this may take a while" message, and then, some seconds after, <i>Aria2</i> downloading the files, while constantly printing out basic info of its progress, like percentage, remaining time, etc...

After upgrading <i>Apt-Fast</i> to 1.9+ and <i>Aria2</i> to 1.33.1, I noted that:

* The "Working... this may take a while" message, instead of remaining there when <i>Aria2</i> starts, it becomes invisible

* <i>Aria2</i>, instead of constantly printing basic info every second and printing overall progress of all files being downloaded each 5 mins (More or Less), it just shows the quantity of files to be downloaded at the start and ONLY shows a message if a file gets completely downloaded (Not like before, when info was printed no matter what)

These signals where enough for me to start experimenting with <i>Apt-Fast</i> & <i>Aria2</i>, just to find out that:

* Only if both packages are downgraded to 1.8.6 & 1.19.0 [Respectively], things work as expected again
* If any of the packages remain "updated", things will keep behaving strange

Extra Info:

* If I download a list of files using only <i>Aria2</i> by itself, it keeps printing basic info every sec and overall progress at a constant rate normally
* <i>Apt-Fast</i> sometimes prints basic info, but in a non-formatted way and also the info isn't refreshed, so a second later, it becomes outdated...
* If <i>Apt-Fast</i> is interrupted while working with "Ctrl + C", sometimes it prints all the info (Basic & Overall), but again, non-formatted.

Is <i>Apt-Fast</i>'s or <i>Aria2</i>'s error?

To clarify things, this IS NOT a malfunction, it's just an annoying visual bug.

EDIT: Almost forgot to mention that I've successfully replicated this bug in:

* Linux Mint 18 (Ubuntu 16.04)
* Windows 10 (Inside Windows Linux Subsystem [Ubuntu 16.04])

**Comment by Lasall** [comment]
Thank you for this detailed report. Can you maybe share a screenshot that displays the visual issues?

As of version 1.9 apt-fast also uses sed to parse all the aria output, maybe you could remove that and test if it works that way.

**Comment by guekho64** [comment]
I'll try to send some evidence of the bug...

BTW, Where do I find the sed command?

In <i>apt-fast.conf</i>?

**Comment by Lasall** [comment]
https://gist.github.com/Lasall/3e9a692be1cb3a862466ad82d417c258

I just removed all the 'sed ... ' putting the apt-fast prefix to the executed _DOWNLOADER command. This is the script file in bin.

**Comment by guekho64** [comment]
Ah! Just in time:

https://github.com/guekho64/PersonalStuff/blob/master/Bug%20Evidence.zip

It's a ZIP with a video inside. Successfully reproduced the aforementioned bug!

**Comment by Lasall** [comment]
Did you reproduce it with the stripped down version? I will take a look at
the video in a couple of hours.

**Comment by guekho64** [comment]
After, copying & pasting your edited <i>Apt-Fast</i> version, and after looking more closely to your source code, I can say that:

* New version (1.9.3-2?) without sed, seems to bring back the constant info output from <i>Aria2c</i>
* 1.9.3-1 adds a new variable in the script named "REMOVE_WORKING_MESSAGE" (Line 503), which, as its name suggests, removes the "Working..." message

So...is this issue solved now? (Or further testing is needed?)

**Comment by Lasall** [comment]
The only downside is it removes the output prefix from the aria command.
That being said I have to take a closer look later before dropping this
feature (it's working for me). Some terminal magic going on, others might
know more.

**Comment by Lasall** [comment]
Thank you for helping on this issue. Eight minutes into the video I could see it too ;)

**Comment by guekho64** [comment]
It's my pleasure to help this "apt" enhancer to keep getting better! 

<i><b>Thanks by all your time you spent reading & solving this issue!</i></b>
