### ISSUE TITLE
Debian package: failed parsing of multiline config values

### ISSUE THREAD

**Issue by SwooshyCueb** [ilikenwf/apt-fast#141]
So this is an odd one.

I'm upgrading from the `apt-fast` in the old PPA (package was based on https://github.com/ilikenwf/apt-fast/commit/3a6bd771bdbbacb21527d593f9fb54909dc1a56f ) and the new package fails to configure because `postinst` chokes on my mirrors list:
```
MIRRORS=( 'http://us.archive.ubuntu.com/ubuntu,http://mirror.metrocast.net/ubuntu,http://mirror.us.leaseweb.net/ubuntu,http://mirror.nodesdirect.com/ubuntu,http://mirrors.advancedhosters.com/ubuntu,http://fireball-public.phys.wvu.edu/mirror/ubuntu,http://reflector.westga.edu/repos/Ubuntu/archive,http://mirror.jmu.edu/pub/ubuntu'
          'http://packages.linuxmint.com,http://mirror.metrocast.net/linuxmint-packages,http://mirrors.advancedhosters.com/linuxmint/packages,http://fireball-public.phys.wvu.edu/mirror/linuxmint-packages,http://mirror.jmu.edu/pub/linuxmint/packages'
          'http://www.bouml.fr/apt/xenial,http://bouml.free.fr/apt/xenial' )
```

The strange thing is, though, if I download the tarball from launchpad and run the `postinst` script myself with `sudo ./postinst configure`, it works fine. But I have to move the script out of the `debian` folder first or it tries to parse `debian/templates` and dies.

EDIT:
Okay now I've actually looked at the `apt-fast.conf` that `postinst` spits out after doing its thing, and it actually *didn't* work fine:
```
MIRRORS=( 'http://us.archive.ubuntu.com/ubuntu,http://mirror.metrocast.net/ubuntu,http://mirror.us.leaseweb.net/ubuntu,http://mirror.nodesdirect.com/ubuntu,http://mirrors.advancedhosters.com/ubuntu,http://fireball-public.phys.wvu.edu/mirror/ubuntu,http://reflector.westga.edu/repos/Ubuntu/archive,http://mirror.jmu.edu/pub/ubuntu'
#          'http://packages.linuxmint.com,http://mirror.metrocast.net/linuxmint-packages,http://mirrors.advancedhosters.com/linuxmint/packages,http://fireball-public.phys.wvu.edu/mirror/linuxmint-packages,http://mirror.jmu.edu/pub/linuxmint/packages'
#          'http://www.bouml.fr/apt/xenial,http://bouml.free.fr/apt/xenial' )
```

It commented out the second and third lines and left the array open.

But the fact remains that it errors out when being run by dpkg, but not when being run manually, which may indicate some other problem.

**Comment by Lasall** [comment]
Thank you for reporting this issue! Can you provide the error messages when the script fails please?

**Comment by Lasall** [comment]
The config/postinst scripts from the Debian package can't handle multiline config values. (To prevent an update of the package to fail you can temporarily put the MIRRORS entry into a single line.)

**Comment by Lasall** [comment]
A fix is pushed to the PPA. Packages should be built within a few hours.
