### ISSUE TITLE
Please update ppa for bionic

### ISSUE THREAD

**Issue by Surendrajat** [ilikenwf/apt-fast#143]
Couldn't add ppa on Ubuntu 18.04. Got this:
```bash
$ sudo add-apt-repository ppa:apt-fast/stable
Cannot add PPA: 'ppa:~apt-fast/ubuntu/stable'.
ERROR: '~apt-fast' user or team does not exist.
```

**Comment by Lasall** [comment]
The PPA already exists: https://launchpad.net/~apt-fast/+archive/ubuntu/stable?field.series_filter=bionic

**Comment by heldaccountable** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders.

Lueosi, you will not get away with abuse. Stop this.

**Comment by uverybad** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.
