### ISSUE TITLE
Why use "have" command in "apt-fast/completions/bash/apt-fast"?

### ISSUE THREAD

**Issue by massongit** [ilikenwf/apt-fast#145]
In `apt-fast/completions/bash/apt-fast`, `have` command is used.
https://github.com/ilikenwf/apt-fast/blob/00fe0f072bcdd52a6067dad0a8f26214e13c29cd/completions/bash/apt-fast#L5
Why use this command?

**Comment by Lasall** [comment]
It's a [wrapper around `type`](https://stackoverflow.com/a/12874971/770468). That being said, it's not used in the apt-get/apt completions (as of 1.6.1). Does the bash completion work?

**Comment by massongit** [comment]
@Lasall I installed `apt-fast` on Ubuntu 16.04 LTS via Ubuntu PPA (`ppa:apt-fast/stable`).
Bash completion for `apt` works, but that for `apt-fast` doesn't work.

**Comment by massongit** [comment]
@Lasall Replacing `have` with `type` make bash completion effective, so it seems that there is a problem with bash completion version.

**Comment by Lasall** [comment]
Thank you for reporting this issue. I removed the "have" part as it's not used by other completions either.

**Comment by heldaccountable** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders.

Lueosi, you will not get away with abuse. Stop this.

**Comment by uverybad** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.
