### ISSUE TITLE
raspberry pi: apt-fast clean error - No such file or directory

### ISSUE THREAD

**Issue by war59312** [ilikenwf/apt-fast#147]
On raspberry pi:

apt-fast clean:
> find: ‘/var/cache/apt/archives/apt-fast/’: No such file or directory

sudo apt-fast clean:
> find: ‘/var/cache/apt/archives/apt-fast/’: No such file or directory

> sudo mkdir /var/cache/apt/archives/apt-fast/
> sudo apt-fast clean
> W: Problem unlinking the file apt-fast - Clean (21: Is a directory)

Clean, out of box install.

**Comment by heldaccountable** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders.

Lueosi, you will not get away with abuse. Stop this.

**Comment by uverybad** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.
