### ISSUE TITLE
How to change the default downloader from aria2 to axel?

### ISSUE THREAD

**Issue by Feliz-S** [ilikenwf/apt-fast#148]

**Comment by gothicVI** [comment]
https://github.com/ilikenwf/apt-fast/blob/master/README.md#downloadmanager-command

**Comment by Feliz-S** [comment]
i know this but every time i'm modifying this i'm missing something .can you share the code it'll be really helpful.Thanks in advance

**Comment by Lasall** [comment]
Maybe something like this will work (not tested):
`sed '1d;N;N;s/\n/\t/g;s/\([^\t]\+\)\t[^\t]\+\t out=\(.*\)/-o \2 \1/'
"${DLLIST}" | xargs -L1 axel`

Plus some extra settings like number of connections etc.

Axel can however only download one file simultaneously. Therefore to
download different packages in parallel this command would be slower than
default apt-get (which supports parallel download from different servers).

**Comment by Feliz-S** [comment]
axel is not receiving any data packets with this.Anyway Thanks

**Comment by Lasall** [comment]
Setting the command to
```sh
_DOWNLOADER='sed "1d;:a;N;\$!ba;s/\n/\t/g;s/\([^\t]\+\)\(\t checksum=[^\t]\+\)\?\t out=\([^\t]\+\)\(\t\)\?/-o \3 \1\n/g" ${DLLIST} | xargs -L1 axel'
```
in the config file uses axel as download manager (sequential download).

**Comment by Feliz-S** [comment]
I'll try this.Thank you
