### ISSUE TITLE
Please provide a shell script to uninstall this

### ISSUE THREAD

**Issue by Feliz-S** [ilikenwf/apt-fast#149]
Whenever i use Git  it's  using apt-fast as a shell wrapper and it's so slow to download

**Comment by Lasall** [comment]
Please specify, how do you use apt-fast with git?

**Comment by Feliz-S** [comment]
how can i uninstall it?
without creating any problem?

**Comment by Lasall** [comment]
Did you use the quick-install script? It installs at:
```
/usr/local/sbin/apt-fast
/etc/apt-fast.conf
```
Deleting these two files is sufficient in removing apt-fast (as long as it's not installed as deb).

**Comment by Feliz-S** [comment]
already did this .thanks btw
