### ISSUE TITLE
Odd output spacing (i.e. line feeds /wo carriage returns)

### ISSUE THREAD

**Issue by Kolano** [ilikenwf/apt-fast#151]
Some install details seem to output oddly, where line feeds occur /wo carriage returns, so excessive indentation is seen (i.e. each line is indented the width of the prior line)

```
0 upgraded, 57 newly installed, 0 to remove and 0 not upgraded.
                                                               Need to get 0 B/107 MB of archives.
                                                                                                  After this operation, 248 MB of additional disk space will be used.i
```

**Comment by Lasall** [comment]
What platform are you using? This is a package manager output, does the package manager shows fine when invoked directly?

**Comment by Lasall** [comment]
Closed due to not enough information / not reproducible. Feel free to reopen.
