### ISSUE TITLE
Support for fish shell?

### ISSUE THREAD

**Issue by prijindal** [ilikenwf/apt-fast#152]
It would be really good if there were completions for fish shell

**Comment by Lasall** [comment]
It´s possible to take the apt-get completion (e.g. from https://github.com/fish-shell/fish-shell/blob/master/share/completions/apt-get.fish) and adapt it to apt-fast.

**Comment by Lasall** [comment]
If it works you can make a pull request.

**Comment by Lasall** [comment]
@prijindal How is the completion working?

**Comment by hunter-richardson** [comment]
See #159 .

**Comment by prijindal** [comment]
@Lasall Sorry for replying so late.
I have not run any tests, but I have been using this for my general use and i have not find any issues

**Comment by Lasall** [comment]
Thank you for everyone involved :)
