### ISSUE TITLE
prompts for confirmation even if there's nothing to download

### ISSUE THREAD

**Issue by jayenashar** [ilikenwf/apt-fast#157]
```
 Working... this may take a while.
# apt-fast mirror list: Thu  7 Feb 14:14:18 AEDT 2019
 If you want to download the packages on your system press Y else n to abort. [Y/n]:  
No files to download.
```

**Comment by gothicVI** [comment]
What is your system environment? OS? version? distribution?
What command exactly did you enter? What were the circumstances? What behavior did you expect?

**Comment by jayenashar** [comment]
```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.7 (stretch)
Release:        9.7
Codename:       stretch
```

```
sudo apt-fast upgrade
```

Circumstance: No files to download.  0 upgraded, 0 newly installed

Expected behaviour: No prompt, like `apt upgrade` and `apt-get upgrade`.

**Comment by Lasall** [comment]
You are using an old version of apt-fast. How did you install it? Please follow: https://github.com/ilikenwf/apt-fast#ubuntu-ppa

**Comment by Lasall** [comment]
I just see your related issue #156 that you have trouble installing the package on Debian, will comment there.

**Comment by jayenashar** [comment]
i used the [debian method](https://github.com/ilikenwf/apt-fast#debian-and-derivates) (though obviously before you wrote it).

`apt-cache policy apt-fast` shows i have `1.9.5-1~ubuntu18.04.1` installed

i have this in the header:

```
# apt-fast v1.9
# Use this just like aptitude or apt-get for faster package downloading.
#
# Copyright: 2008-2012 Matt Parnell, http://www.mattparnell.com
# Improvements, maintenance, revisions - 2012, 2017-2018 Dominique Lasserre
```

i believe i am running the latest version, and this is still an issue.  please consider reopening this issue.

i have just noticed that `apt-fast upgrade` does NOT have this issue while `sudo apt-fast upgrade` does.

**Comment by Lasall** [comment]
Can you show

```
sudo which apt-fast
```

You definitely have some old version on your system, because the question (if you want to download packages) has changed in newer versions.
