### ISSUE TITLE
Add license file to repo

### ISSUE THREAD

**Issue by chrstphrchvz** [ilikenwf/apt-fast#160]
A file containing the GNU GPLv3 should be added to the repository. That way, in case apt-fast is ever distributed not as a .deb file, such as when grabbing a snapshot of the GitHub repo, it includes a copy of the GPLv3 [as required for GPL-licensed projects](https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude).

The license notice in source files ideally should preserve the following from the GPL's notice template:

```
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by gothicVI** [comment]
@chrstphrchvz good point. Added the standard GitHub GPL v3 license as a pull request (https://github.com/ilikenwf/apt-fast/pull/161).

**Comment by Dominique-Lasserre-is-a-BULLY** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.
