### ISSUE TITLE
apt-get vs. apt-fast speed comparisons

### ISSUE THREAD

**Issue by MichaIng** [ilikenwf/apt-fast#163]
Are there any actual speed comparisons available? Whenever I tried it (choosing the 10 fastest mirrors via `netselect-apt`, testing with download lxde + dependencies, so large amount of concurrent downloads, reverting system (VM) with snapshot to have identical testing conditions), apt-fast is usually slower. The overhead of loading Aria2 and contacting each mirror etc until the actual downloads start, simply takes too much time. And single nearby APT mirrors in my case are fast enough to moreless fill my 100 Mbit download bandwidth, which most likely is the strongest reason for apt-fast not being able to play out it's theoretical strength.

So what sounds reasonable in the first place turns out to be a non-beneficial overhead (I can only speak for my local setup, or course!). To benefit enough from concurrent downloads, so that the software-wise overhead is outweigh, one requires a very fast download bandwidth while having only comparable slow APT mirrors available. This combination naturally is unlikely: If one can get a fast internet connection, then the nearby APT mirrors will have that too.

Finally Debian seems to do a good job with APT tools already. If there was a real benefit for most users, I guess they would at least have considered to implement similar capabilities to apt-get as well?
_____________
However since I could run tests only on my local systems + network setup + location, I am interested on other benchmarks/comparisons + which countries/locations. Sadly web search didn't give any result. I find many guides about how to install and use apt-fast and recommendations to do so, but not a single actual download time comparison with bare `apt-get`.

And since also I couldn't find a single issue here that deals with this question, I am opening it 😉.

**Comment by Noext** [comment]
hello, i really want to see some benchmarks too.

running a 1k+ packages install with apt-fast take the same time as with apt, and like Michalng i have plenty left over on my bandwidth.

**Comment by MichaIng** [comment]
@Noext 
It really seems while everyone sees the great idea and theoretical benefit of `apt-fast` (reading through all the online guides), no one asked the most important question: Is it as well practically faster?

Perhaps it was faster in the past, when Debian APT mirrors were rare, not sure... I don't want to destroy the whole project, but indeed if no one can practically measure significantly faster overall download speeds, it is of course a useless overhead.

For me this question is important since we have regularly users asking to implement `apt-fast` support. And I don't want to implement something where no one has any real benefit from 😉.

**Comment by gothicVI** [comment]
Caveat: more of a gut feeling - no independent measurement, but I personally see a vast speedup when downloading large files as this is more suitable to exceed bandwidth. Small files are usually as fast as a sequential download.

**Comment by MichaIng** [comment]
@gothicVI 
Hmm, with single large files of course this is impossible, it requires multiple large files to at least theoretically grant a benefit.

But I also ran tests with multiple packages, each large file size (java jdk/jre and such), but no difference. One must construct a very unlikely theoretical APT queue to have a benefit then, e.g.:
- Amount of packages at best = amount of configured APT repos or multiples of it.
- All packages large and moreless same size.
- Single APT repo only allowing download speed that matches moreless (( client_download_bandwidth/parallel_download_count )).
- "Practically" this is veeery unlikely, which is why I am searching for "real" benchmarks, and, sorry, but measurements instead of "feelings" 😉.

**Comment by gothicVI** [comment]
@MichaIng  as a proper test, you could download all kernel images available in the repo using both methods multiple times. This should be at least 20 files of around 10 MB size. Or kernel modules with ~40 MB size for a large file test.

**Comment by MichaIng** [comment]
@gothicVI 
Yeah sounds like the best matching queue. However this is far away from any real situation and I did enough tests to know for sure that `apt-fast` is a degradation on all my systems. What I am looking for is users, e.g. from certain countries/locations, where it is a significant benefit in most "real" situations.

Even that my online research didn't give any result, I can't believe that this project is developed for now 8 years and promoted in many blogs and guides, if there was really no benefit for at least a small user base.

**Comment by guekho64** [comment]
@MichaIng I'm not aware if any tests actually exist over this specific topic, but in my personal experience, `apt-fast` downloads packages way faster than `apt-get`.

In fact, what makes the difference here is `aria2c`, the program that `apt-fast` uses under the hood. 

Downloading any kind of file using `aria2c` rather than any other program (`wget`, `curl`...) is way more efficient for me.

I'm not sure if I'm a rare case over the internet, or if my network isn't properly configured, but I can confirm `apt-fast` works for me...

**Comment by MichaIng** [comment]
@guekho64 
Interesting, you mean `aria2c` is faster in your case even when downloading just a single package? I though they all use the same protocol after all so when TCP is established the download itself runs exactly the same for all of those download tools 🤔.

Read a bid and indeed it seems that the strength of aria2 is that it can also download a single file from multiple sources concurrently. So it should be in theory as well faster for single large downloads. However whatever I do, `apt-fast` is slower here:
```
root@VM-Stretch:/tmp# time apt-get download openjdk-8-jre-headless openjdk-8-jdk-headless
Get:1 http://artfiles.org/debian stretch/main amd64 openjdk-8-jdk-headless amd64 8u212-b01-1~deb9u1 [8,247 kB]
Get:2 http://artfiles.org/debian stretch/main amd64 openjdk-8-jre-headless amd64 8u212-b01-1~deb9u1 [27.3 MB]
Fetched 35.5 MB in 7s (4,874 kB/s)

real    0m8.442s
user    0m3.084s
sys     0m1.104s
root@VM-Stretch:/tmp# rm openjdk-8-j*
root@VM-Stretch:/tmp# time apt-fast download openjdk-8-jre-headless openjdk-8-jdk-headless
openjdk-8-jdk-headless                   8u212-b01-1~deb9u1       7.9MiB
openjdk-8-jre-headless                   8u212-b01-1~deb9u1        26MiB
Download size: 34MiB

06/06 17:35:34 [NOTICE] Downloading 2 item(s)
[DL:4.8MiB][#ad1dc9 7.5MiB/7.8MiB(96%)][#88f344 25MiB/25MiB(99%)]
06/06 17:35:42 [NOTICE] Verification finished successfully. file=/tmp/openjdk-8-jre-headless_8u212-b01-1~deb9u1_amd64.deb

06/06 17:35:42 [NOTICE] Download complete: /tmp/openjdk-8-jre-headless_8u212-b01-1~deb9u1_amd64.deb

06/06 17:35:42 [NOTICE] Verification finished successfully. file=/tmp/openjdk-8-jdk-headless_8u212-b01-1~deb9u1_amd64.deb

06/06 17:35:42 [NOTICE] Download complete: /tmp/openjdk-8-jdk-headless_8u212-b01-1~deb9u1_amd64.deb

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
88f344|OK  |   3.6MiB/s|/tmp/openjdk-8-jre-headless_8u212-b01-1~deb9u1_amd64.deb
ad1dc9|OK  |   1.0MiB/s|/tmp/openjdk-8-jdk-headless_8u212-b01-1~deb9u1_amd64.deb

Status Legend:
(OK):download completed.

real    0m9.632s
user    0m2.416s
sys     0m1.652s
```
#### Large amount of small packages:
```
root@VM-Stretch:/tmp# time apt-get download lx*
...
Fetched 16.3 MB in 6s (2,502 kB/s)

real    0m8.084s
user    0m2.724s
sys     0m0.778s
root@VM-Stretch:/tmp# rm lx*
root@VM-Stretch:/tmp# time apt-fast download lx*
...
Status Legend:
(OK):download completed.

real    0m13.672s
user    0m7.581s
sys     0m6.096s
```
____________
#### Established cable connection (above was WiFi):
```
root@VM-Stretch:/tmp# time apt-get download openjdk-11-jdk-headless
Get:1 http://ftp.de.debian.org/debian buster/main amd64 openjdk-11-jdk-headless amd64 11.0.3+1-1 [207 MB]
Fetched 207 MB in 18s (11.5 MB/s)

real    0m19.806s
user    0m10.038s
sys     0m6.655s
root@VM-Stretch:/tmp# rm openjdk-11-jdk-headless_11.0.3+1-1_amd64.deb
root@VM-Stretch:/tmp# time apt-fast download openjdk-11-jdk-headless
openjdk-11-jdk-headless                  11.0.3+1-1               198MiB
Download size: 198MiB

06/06 19:34:37 [NOTICE] Downloading 1 item(s)
[#c7f343 197MiB/197MiB(100%) CN:0] [Checksum:#c7f343 189MiB/197MiB(95%)]
06/06 19:34:59 [NOTICE] Verification finished successfully. file=/tmp/openjdk-11-jdk-headless_11.0.3+1-1_amd64.deb

06/06 19:34:59 [NOTICE] Download complete: /tmp/openjdk-11-jdk-headless_11.0.3+1-1_amd64.deb

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c7f343|OK  |    10MiB/s|/tmp/openjdk-11-jdk-headless_11.0.3+1-1_amd64.deb

Status Legend:
(OK):download completed.

real    0m24.068s
user    0m8.724s
sys     0m6.838s
```
#### With kernel packages, as suggested, which provide a typical share between smaller and larger packages:
```
root@VM-Stretch:/tmp# time apt-get download linux-image*amd64
Get:1 http://ftp.de.debian.org/debian buster/main amd64 linux-image-amd64 amd64 4.19+105 [8,056 B]
Get:2 http://ftp.de.debian.org/debian buster/main amd64 linux-image-cloud-amd64 amd64 4.19+105 [8,068 B]
Get:3 http://ftp.de.debian.org/debian buster/main amd64 linux-image-rt-amd64 amd64 4.19+105 [8,100 B]
Get:4 http://ftp.de.debian.org/debian buster/main amd64 linux-image-4.19.0-5-amd64 amd64 4.19.37-3 [47.6 MB]
Get:5 http://ftp.de.debian.org/debian buster/main amd64 linux-image-4.19.0-5-cloud-amd64 amd64 4.19.37-3 [15.2 MB]
Get:6 http://ftp.de.debian.org/debian buster/main amd64 linux-image-4.19.0-5-rt-amd64 amd64 4.19.37-3 [47.7 MB]
Fetched 111 MB in 11s (9,357 kB/s)

real    0m13.364s
user    0m7.264s
sys     0m4.186s
root@VM-Stretch:/tmp# rm linux-image-*
root@VM-Stretch:/tmp# time apt-fast download linux-image*amd64
linux-image-4.19.0-5-amd64               4.19.37-3                 46MiB
linux-image-4.19.0-5-cloud-amd64         4.19.37-3                 15MiB
linux-image-4.19.0-5-rt-amd64            4.19.37-3                 46MiB
linux-image-amd64                        4.19+105                 7.9KiB
linux-image-cloud-amd64                  4.19+105                 7.9KiB
linux-image-rt-amd64                     4.19+105                 8.0KiB
Download size: 106MiB

06/06 19:36:24 [NOTICE] Downloading 6 item(s)

06/06 19:36:24 [NOTICE] Verification finished successfully. file=/tmp/linux-image-amd64_4.19+105_amd64.deb

06/06 19:36:24 [NOTICE] Download complete: /tmp/linux-image-amd64_4.19+105_amd64.deb

06/06 19:36:24 [NOTICE] Verification finished successfully. file=/tmp/linux-image-rt-amd64_4.19+105_amd64.deb

06/06 19:36:24 [NOTICE] Download complete: /tmp/linux-image-rt-amd64_4.19+105_amd64.deb

06/06 19:36:25 [NOTICE] Verification finished successfully. file=/tmp/linux-image-cloud-amd64_4.19+105_amd64.deb

06/06 19:36:25 [NOTICE] Download complete: /tmp/linux-image-cloud-amd64_4.19+105_amd64.deb
[DL:10MiB][#1bd52c 19MiB/45MiB(42%)][#b5b4a4 14MiB/14MiB(97%)][#214366 18MiB/45MiB(41%)]
06/06 19:36:30 [NOTICE] Verification finished successfully. file=/tmp/linux-image-4.19.0-5-cloud-amd64_4.19.37-3_amd64.deb

06/06 19:36:30 [NOTICE] Download complete: /tmp/linux-image-4.19.0-5-cloud-amd64_4.19.37-3_amd64.deb
[DL:10MiB][#1bd52c 45MiB/45MiB(100%)][#214366 45MiB/45MiB(100%)] [Checksum:#214366 14MiB/45MiB(32%)](+1)
06/06 19:36:34 [NOTICE] Verification finished successfully. file=/tmp/linux-image-4.19.0-5-rt-amd64_4.19.37-3_amd64.deb

06/06 19:36:34 [NOTICE] Download complete: /tmp/linux-image-4.19.0-5-rt-amd64_4.19.37-3_amd64.deb

06/06 19:36:35 [NOTICE] Verification finished successfully. file=/tmp/linux-image-4.19.0-5-amd64_4.19.37-3_amd64.deb

06/06 19:36:35 [NOTICE] Download complete: /tmp/linux-image-4.19.0-5-amd64_4.19.37-3_amd64.deb

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
239e19|OK  |   1.2MiB/s|/tmp/linux-image-amd64_4.19+105_amd64.deb
266f7f|OK  |   1.2MiB/s|/tmp/linux-image-rt-amd64_4.19+105_amd64.deb
75d961|OK  |    25KiB/s|/tmp/linux-image-cloud-amd64_4.19+105_amd64.deb
b5b4a4|OK  |   2.6MiB/s|/tmp/linux-image-4.19.0-5-cloud-amd64_4.19.37-3_amd64.deb
214366|OK  |   4.6MiB/s|/tmp/linux-image-4.19.0-5-rt-amd64_4.19.37-3_amd64.deb
1bd52c|OK  |   4.5MiB/s|/tmp/linux-image-4.19.0-5-amd64_4.19.37-3_amd64.deb

Status Legend:
(OK):download completed.

real    0m13.596s
user    0m5.001s
sys     0m3.752s
```
I also played around with different APT mirrors. Indeed it stands and falls with the speed provided by the APT mirror. The `deb.debian,org` CDN as well as `netselect-apt` did not get me the fastes mirror(s). I think those check more the ping speeds/closest locations but do not (correctly) check the max download speed they offer. I found some that did not max out my bandwidth with cable connected, even those were located close and recommended by `netselect-apt` as fastest one.

So I guess there might be indeed locations where the own bandwidth is higher then the max download speed that is possible from any single APT mirror and then indeed downloading from multiple ones concurrently large files will be faster. However in reality when you install typical APT packages or upgrade, you will face a larger amount of smaller packages, libraries or available updates and with this the background calculations/preparations of `apt-fast` seem to be a too large overhead. Perhaps it is also a question of configuration. I left everything as is, besides `_MAXNUM=10` and adding the 10 fastest APT mirrors, starting with the fastest one that is also added to `sources.list`. Perhaps in case of smaller files it tries to chunk the download too quickly where it would be better to only do this for larger files, not sure.

**Comment by MarcoFalke** [comment]
I think the readme should mention that apt-fast might slow down the process when you are connected to a fast and close-by mirror.

**Comment by guekho64** [comment]
In fact, there are many factors that can potentially impact on your daily use, either external (mirrors, speed, location...) or internal (bad config, messed-up system, old packages...)

That being said, here's a list with stuff I do each time I install or reinstall apt-fast:

* `apt-get --purge autoremove aria2c apt-fast && apt-get install apt-fast` -> Just in case I'm reinstalling

* `dpkg-reconfigure apt-fast` -> `apt-get` as backend; Every time it asks for a number, I try to input a big number or the max allowed for an option

* Download and compile lastest aria2 release, with OpenSSL support

* Create a `.deb` file from compiled files

* Override `aria2c` package  by installing the newly generated package -> I wouldn't recommend just doing a `make install`, as it may confuse apt later

**Comment by MichaIng** [comment]
@guekho64 
Thanks for your suggestion.

Regular purge, recompile, reinstall is indeed a huge overkill. That costs me much more time and nerves than the little (if ever) saved time by using apt-fast at all. Simple updates (apt or git clone + compile script or whatever) should be sufficient, otherwise either the devs or package maintainers do something wrong or the sys admin. Also I read changelogs usually and there is really not much performance-related that could affect the final download speed done lately, neither apt-fast, or Aria2-side.

Really, I am pretty sure it is the concept itself that simply cannot have a benefit in every case, thinking through it that also totally makes sense.

**Comment by guekho64** [comment]
>Really, I am pretty sure it is the concept itself that simply cannot have a benefit in every case, thinking through it that also totally makes sense

@MichaIng, I totally agree.

>Regular purge, recompile, reinstall is indeed a huge overkill. That costs me much more time and nerves than the little (if ever) saved time by using apt-fast at all...

If you're planning to do this manually, obviously It'll become a time-consuming task. Fortunately, I don't do this step by step, as I made my own scripts for this specific purpose. :construction:

**Comment by MichaIng** [comment]
@guekho64 
> If you're planning to do this manually, obviously It'll become a time-consuming task. Fortunately, I don't do this step by step, as I made my own scripts for this specific purpose. 🚧

Of course you can effort time to write a script and even create a cron job or systemd unit to update apt-fast automatically regularly etc. The question stays the same if this time effort can ever be compensated by apt-fast time savings. I already automate APT upgrades, hence there it doesn't play a role, so it's only about ondemand package installs. If download speeds doubled, this makes sense, if it is +-0 or even negative on all my tests, then it was a waste of time. To at least have an idea in which circumstances one can really expect benefits, is IMO a very important information. As I mentioned above, when I read across all those guides around the web, I get the impression that many users use apt-fast while not gaining any benefit over apt-get by this, because no-one really compared speeds. The mill then drives itself while being no benefit or only downside in 90% of cases, or same effort could have much more effect if users test and choose some nearby fast APT mirror with apt-get, away from system default.

**Comment by guekho64** [comment]
@MichaIng It's kind of weird that such a good program could perform so poorly while executing within some specific environment or circumstances...

In fact, `apt-fast` and `aria2` are the first packages I try to download every time I'm configuring a new Debian or Ubuntu installation.

To demonstrate my point, I'll run the exact above tests within a `Live Session` of `Linux Mint 19.2 MATE amd64`, with no changes to `apt` configuration nor `apt` mirror list, aside from installing `apt-fast` following [official installation instructions.](https://github.com/ilikenwf/apt-fast#ubuntu-ppa)

Also, I didn't compile latest `aria2` version for these tests:

<details><summary><b><code>aria2c -v</code> Output</b></summary>

![image](https://user-images.githubusercontent.com/8020999/69907346-8e9a7f00-13cb-11ea-9ba9-f5e119f68165.png)
</details>

<details><summary><b><code>apt-fast -v</code> Output</b></summary>

![image](https://user-images.githubusercontent.com/8020999/69907356-bb4e9680-13cb-11ea-9ba6-ed2b2047361d.png)
</details>

<h1><b>Test 1</b></h1>

<details><summary><i><code>apt-get</code></i></summary>

![image](https://user-images.githubusercontent.com/8020999/69907392-9870b200-13cc-11ea-894a-6dcb14020330.png)
</details>

<details><summary><i><code>apt-fast</code></i></summary>

![image](https://user-images.githubusercontent.com/8020999/69907430-7166b000-13cd-11ea-98bb-9909a96b93b0.png)
</details>

<h1><b>Test 2</b></h1>

<details><summary><i><code>apt-get</code></i></summary>

![image](https://user-images.githubusercontent.com/8020999/69907495-e639ea00-13cd-11ea-98ed-a3fe7c0121d1.png)
</details>

<details><summary><i><code>apt-fast</code></i></summary>

![image](https://user-images.githubusercontent.com/8020999/69907510-197c7900-13ce-11ea-86c3-af344994b724.png)
</details>

<h1><b>Test 3</b></h1>


<details><summary><i><code>apt-get</code></i></summary>

![image](https://user-images.githubusercontent.com/8020999/69907655-5d707d80-13d0-11ea-992e-1503b466c466.png)
</details>

<details><summary><i><code>apt-fast</code></i></summary>

![image](https://user-images.githubusercontent.com/8020999/69907674-b6d8ac80-13d0-11ea-94d3-e74cc60e3420.png)
</details>

I'd do the fourth test as well, but after downloading all these packages, now I'm tired of looking without doing anything...

Anyway, I think this will be enough to probe that `apt-fast` is the fastest in this scenario, while `apt-get` isn't, and that's exactly why I prefer and recommend `apt-fast`: It really helps me downloading files, whether they're files from internet, or packages from `apt` repos.

I have no clue what could be happening in your case, as taking in account everything as a whole would be quite complicated... (mirrors, internet speed, local network load, server workload, and many other factors...)

**Comment by MichaIng** [comment]
@guekho64 
Many thanks for your tests. Indeed your single server `~280 kB/s` are very slow, hence it is very expected that multiple download streams speed this up roughly by the factor of concurrent download servers minus some CPU time.

But did you try some other local APT mirror instead? `archive.ubuntu.com` AFAIK is a fixed central server, no CDN and clearly no local mirror. I just found the easy method on Ubuntu to have APT choosing a local mirror automatically by using `mirror://mirrors.ubuntu.com/mirrors.txt` in `sources.list`: https://askubuntu.com/a/37754

**Comment by guekho64** [comment]
After issuing an `apt-get update` and seeing the results...Do you really think downloads will get better through this method? Just saying...

<details><summary><i>Before</i></summary>

![image](https://user-images.githubusercontent.com/8020999/70197990-28677200-16d3-11ea-85e1-cf85c93d047a.png)

</details>

<details><summary><b>After</b></summary>

![image](https://user-images.githubusercontent.com/8020999/70197952-0d94fd80-16d3-11ea-8986-9048b80ef1fe.png)

</details>

**Comment by MichaIng** [comment]
@guekho64 
Jep, now the actual package download speed would be interesting.

Just another source for this method: https://linuxconfig.org/how-to-select-the-fastest-apt-mirror-on-ubuntu-linux
I never heard of it (for found something similar) on Debian, might be Ubuntu special as CDN replacement/alternative. On Debian one would use `deb.debian.org` instead which resolves to a close mirror.

Of course one can use a country-based mirror manually as well, e.g. `au.archive.ubuntu.com` for Australia etc, or [netselect](https://github.com/apenwarr/netselect) to find the fastest/closest for you. However netselect seems to be not available via Ubuntu repo anymore and AFAIK it checks find reply time only, not bandwidth.

**Comment by guekho64** [comment]
@MichaIng Recently I haven't been able to experiment, as I've been doing some other things. I'll try your suggestion as soon as possible...

**Comment by sgqy** [comment]
For example.
```
security.ubuntu.com
ppa.launchpad.net
packages.microsoft.com
``` 
They are not nearby servers in the world.

In China they are slow, takes minutes to run `apt update` if these URLs appear. And take longer (sometimes it _pauses_) to run `apt install`. Going through an overseas proxy is much better...

I set concurrency as 500 in `apt-fast` config to bypass these situations. It usually goes full bandwidth if there are multi packages from far servers: Bandwidth is `5MB/s`, while `30KB/s × 30 = 1MB/s`. That is it.

**Comment by MichaIng** [comment]
@sgqy 
Ah that makes sense. I always thought about/tested Debian repositories which have nearby servers on nearly every location. security.debian.org is a single server as well AFAIK, although deb.debian.org/debian-security/ is CDN replacement. Probably such does not exist on Ubuntu. And of course 3rd party repos/PPAs are usually a single server, so there it totally makes sense.

Okay I think I got the situations where apt-fast, respectively Aria2 has its real benefits. Also the further above clarified misunderstanding that there are even no multiple sources.list entries required to have a single file downloaded faster via Aria2 is great already.

I close the issue now and consider adding apt-fast support to our project, probably with some explanation about when this can be beneficial.

**Comment by RydrIsAnAbuseClub** [comment]
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by thebestestseb** [comment]
Reminder that Dominique Lassere aka @Lasall is an abuser who along with his buddies in the hate group Storm Riders has been bullying me for years and is now trying to cover that up.
