### ISSUE TITLE
Remove empty new lines (suggestion)

### ISSUE THREAD

**Issue by Zaczero** [ilikenwf/apt-fast#164]
First of all, I love this tool! It really saves some time while downloading lots of packages. However I don't like how much free space is being wasted for those new lines.

![](https://i.imgur.com/s1yIJFg.png)

Each line should be populated just like you can see on the normal apt.

![](https://i.imgur.com/td51eq6.png)

Everything is readable and clear. No need for those new lines.
What I'm trying to say is that the apt-fast output doesn't really fit the linux cli style with that.

Maybe you can also remove the /var/cache/apt/apt-fast prefix from the output as it's not that relevant in the upgrade and save some even more space. Simplify it a little bit. No need to print full path each time.

```
05/29 15:38:20 [NOTICE] Download complete: /var/cache/apt/apt-fast/initramfs-tools-bin_0.130ubuntu3.8_amd64.deb
...
05/29 15:38:20 [NOTICE] Download complete: initramfs-tools-bin_0.130ubuntu3.8_amd64.deb
```

I hope that you can do something about that sir ! 🦊

**Comment by Lasall** [comment]
Thank you for your suggestion! This is the exact output of the download manager [aria2](https://aria2.github.io/), so your suggestions regarding output formatting should be redirected there.

**Comment by gothicVI** [comment]
Could [this](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-download-result) be a solution?

**Comment by Zaczero** [comment]
@Lasall thanks for the reply

@gothicVI I don't think so that it will remove those empty spaces. Rather change what info is being displayed

**Comment by gothicVI** [comment]
@Zaczero quoting you:
> Maybe you can also remove the /var/cache/apt/apt-fast prefix from the output as it's not that relevant in the upgrade and save some even more space. Simplify it a little bit. No need to print full path each time.

But it was just a suggestion ;)

**Comment by DominiqueLasserreIsStillAnAbuser** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders and is now trying to cover that up. Lueosi, you will never get away with abuse no matter how many lies you tell. Stop this.

**Comment by DominiqueLasserreIsABully** [comment]
Unfortunately, Dominique Lasserre aka @Lasall is still under the delusion that he can cover up how he and his buddies from the hate group Storm Ryders have been bullying me for years. Listen arsewhole, if you ever want to hope of getting out of this stop trying to layer more lies and bullshit onto what you have done. Come clean, apologize, make amends.

**Comment by DominiqueLasserreAkaLasallIsABully** [comment]
This is yet another reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders. Dominique is now trying to cover that up and you must not let him.

**Comment by whatyoualldidwaswrong** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with this buddies in the hate group Storm Ryders and is now trying to cover that up.

**Comment by Dominique-Lasserre-is-a-BULLY** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.
