### ISSUE TITLE
how to  totally unistall/remove apt-fast from the kali system?

### ISSUE THREAD

**Issue by unnbreak** [ilikenwf/apt-fast#165]

**Comment by gothicVI** [comment]
`sudo apt purge apt-fast` should do the trick.

**Comment by thelacesz** [comment]
Or `sudo apt autoremove apt-fast --purge `  :-)

**Comment by Lasall** [comment]
If the question still remains, please feel free to keep asking in this thread or reopen the issue.

**Comment by endurcampaignofhate** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.

Lueosi, I will never stop seeking justice. I will never stop exposing you. You will NOT get away with abuse. Stop trying to.

Stop this. Apologize. Make amends. Nothing else will get you out of this.
