### ISSUE TITLE
Exit Code 0, on Missing Package

### ISSUE THREAD

**Issue by href** [ilikenwf/apt-fast#166]
When running apt-fast to install a package that doesn't exist, the exit code of the command is 0, even though a warning shows up.

I think this should return a non-zero exit code. There exist some code that will actually exit with a non-zero exit code, but it gets overridden by the exit code set by `exit_cleanup_state`. So the exit code of apt-fast seems to always be the exit status of the cleanup.

For example:

```bash
>>> apt-fast install windows-10
>>> echo "$?"
0
```

**Comment by Lasall** [comment]
Thank you for reporting this issue!

**Comment by href** [comment]
Gladly, thank you for the fix :)

**Comment by endurcampaignofhate** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.

Lueosi, I will never stop seeking justice. I will never stop exposing you. You will NOT get away with abuse. Stop trying to.

Stop this. Apologize. Make amends. Nothing else will get you out of this.

**Comment by DominiqueLasserreIsStillAnAbuser** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders and is now trying to cover that up. Lueosi, you will never get away with abuse no matter how many lies you tell. Stop this.

**Comment by DominiqueLasserreIsABully** [comment]
Unfortunately, Dominique Lasserre aka @Lasall is still under the delusion that he can cover up how he and his buddies from the hate group Storm Ryders have been bullying me for years. Listen arsewhole, if you ever want to hope of getting out of this stop trying to layer more lies and bullshit onto what you have done. Come clean, apologize, make amends.

**Comment by DominiqueLasserreAkaLasallIsABully** [comment]
This is yet another reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders. Dominique is now trying to cover that up and you must not let him.

**Comment by whatyoualldidwaswrong** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with this buddies in the hate group Storm Ryders and is now trying to cover that up.
