### ISSUE TITLE
apt-fast is not showing the missing dependencies for installing a program

### ISSUE THREAD

**Issue by lalitmee** [ilikenwf/apt-fast#167]
Hi Guys,

I noticed this issue when I was trying to install `i3 window manager` by using the command

- Command
```bash
sudo apt-fast install i3
```
- Output
```bash
E: Unable to correct problems, you have held broken packages
```

I got to know the dependency problem when I ran the 
- Command
```bash
sudo apt-get install i3
```
- Output: It told that i3-wm is missing as it is required for i3

I really like apt-fast but this behavior is weird.

**Comment by gothicVI** [comment]
Which version of Ubuntu are you on? Also, what backend are you using for `apt-fast` (`apt`, `apt-get`, or `aptitude`)?

**Comment by lalitmee** [comment]
I am on **Lubuntu 18.04** and how to check for the backend for apt-fast?

**Comment by gothicVI** [comment]
That's strange. I'm running Linux Mint 19.2 which is based on Ubuntu 18.04 and I can find the package `i3-wm` when running `apt search i3 | grep i3-wm`. Can you as well?
Also when I'm running `apt install --dry-run i3`, or `apt-fast install --dry-run i3`, I'm not getting any issues. For the time beeing I'd assume there might be an issue either with your source list or there're some broken packages as indicated by your original post.
Can you double-check that you do not have any broken packages?

**Comment by lalitmee** [comment]
Actually now I installed i3 by giving this command.
```bash
sudo apt-fast install i3 i3-wm
```
But thanks for your support. And I am also using `apt-get` as the backend for the `apt-fast` now.

**Comment by Lasall** [comment]
apt-fast just wraps around apt/apt-get/aptitude and allows those package managers to output errors. So this issue is not related to apt-fast. I'm glad you were able to resolve your package conflict/problem.

If you have more questions feel free to reopen this issue.

**Comment by DominiqueLasserreIsAnAbuser** [comment]
FYI, Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with the rest of the hate group Storm Ryders and is now trying to cover that up.
