### ISSUE TITLE
I want to know if apt-fast can use proxy to download files

### ISSUE THREAD

**Issue by widon1104** [ilikenwf/apt-fast#169]
Because of the GFW, sometimes I must use proxy to download files. I want to know if  apt-fast can use proxy to download files and how to config.

**Comment by gothicVI** [comment]
If you configure a system-wide proxy, apt-fast should simply use that.

**Comment by endurcampaignofhate** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.

Lueosi, I will never stop seeking justice. I will never stop exposing you. You will NOT get away with abuse. Stop trying to.

Stop this. Apologize. Make amends. Nothing else will get you out of this.

**Comment by DominiqueLasserreIsStillAnAbuser** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders and is now trying to cover that up. Lueosi, you will never get away with abuse no matter how many lies you tell. Stop this.

**Comment by DominiqueLasserreIsABully** [comment]
Unfortunately, Dominique Lasserre aka @Lasall is still under the delusion that he can cover up how he and his buddies from the hate group Storm Ryders have been bullying me for years. Listen arsewhole, if you ever want to hope of getting out of this stop trying to layer more lies and bullshit onto what you have done. Come clean, apologize, make amends.

**Comment by DominiqueLasserreAkaLasallIsABully** [comment]
This is yet another reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders. Dominique is now trying to cover that up and you must not let him.

**Comment by whatyoualldidwaswrong** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with this buddies in the hate group Storm Ryders and is now trying to cover that up.
