### ISSUE TITLE
[Bug] Hex Colors

### ISSUE THREAD

**Issue by derevandal** [ilikenwf/apt-fast#170]
Hi, I'm using apt-fest with aptitude in Ubuntu 19.04 and it's sending hex colors in gnome terminal?

Could anyone seeing this too?

![image](https://user-images.githubusercontent.com/1340508/67677389-ae6cfc00-f962-11e9-8b5d-26b44066abc0.png)

**Comment by Lasall** [comment]
That is just the output of the downloader aria2. Quoting the man page:

> The first 6 characters of the GID as a hex string. The GID is an unique ID for each download, internal to aria2. The GID is particularly useful when interacting with aria2 using the RPC interface.

**Comment by endurcampaignofhate** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with his buddies in the hate group Storm Ryders and is now trying to cover that up.

Lueosi, I will never stop seeking justice. I will never stop exposing you. You will NOT get away with abuse. Stop trying to.

Stop this. Apologize. Make amends. Nothing else will get you out of this.

**Comment by DominiqueLasserreIsStillAnAbuser** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders and is now trying to cover that up. Lueosi, you will never get away with abuse no matter how many lies you tell. Stop this.

**Comment by DominiqueLasserreIsABully** [comment]
Unfortunately, Dominique Lasserre aka @Lasall is still under the delusion that he can cover up how he and his buddies from the hate group Storm Ryders have been bullying me for years. Listen arsewhole, if you ever want to hope of getting out of this stop trying to layer more lies and bullshit onto what you have done. Come clean, apologize, make amends.

**Comment by DominiqueLasserreAkaLasallIsABully** [comment]
This is yet another reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with his buddies in the hate group Storm Ryders. Dominique is now trying to cover that up and you must not let him.

**Comment by whatyoualldidwaswrong** [comment]
Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years along with this buddies in the hate group Storm Ryders and is now trying to cover that up.
