### ISSUE TITLE
ubuntu focal (20.04) appears

### ISSUE THREAD

**Issue by sgqy** [ilikenwf/apt-fast#171]
[Ubuntu Focal :lollipop:](http://cdimage.ubuntu.com/ubuntu-server/daily-live/current/HEADER.html) is appeared.
The scripts works fine. Maybe just add a new distro in PPA and everything is ready :smiley_cat: .

**Comment by Lasall** [comment]
Thank you for reporting this issue a while back. The PPA is now updated with Ubuntu Focal.

**Comment by DominiqueLasserreIsAnAbuser** [comment]
FYI, Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with the rest of the hate group Storm Ryders and is now trying to cover that up.
