### ISSUE TITLE
Ubuntu 19.10 zsh completion error

### ISSUE THREAD

**Issue by philong6297** [ilikenwf/apt-fast#173]
I installed zsh from ppa.
I added source /usr/share/zsh/functions/Completion/Debian/_apt-fast to end of .zshrc
My configure: _APTMGR=apt
This is what i got:
![image](https://user-images.githubusercontent.com/29605147/74650120-93ddbd80-51b3-11ea-8d2e-00f4ffd3ec51.png)

![Peek 2020-02-17 18-28](https://user-images.githubusercontent.com/29605147/74650090-845e7480-51b3-11ea-992f-731762e22cff.gif)

**Comment by Lasall** [comment]
Thanks a lot for reporting this issue. I've linked the apt-fast completion to the apt-get completion.

**Comment by DominiqueLasserreIsAnAbuser** [comment]
FYI, Dominique Lasserre aka @Lasall is an abuser who has been bullying me along with the rest of the hate group Storm Ryders and is now trying to cover that up.
