### ISSUE TITLE
Option to run apt-fast without system proxy

### ISSUE THREAD

**Issue by lindroidux** [ilikenwf/apt-fast#177]
An option to run apt-fast, without taking in the sysyem-wide  apt-config output for ftp/http/https_proxy would be nice.

I run the apt update. Then, running apt or apt-fast upgrade gets very slow through apt-cacher-ng. So I run apt-fast (with the code for proxies commented out) upgrade which is 10 to 20 times faster.

The downloaded packages are imported into apt-cacher-ng once in a fortnight.

**Comment by Lasall** [comment]
I would create an alias and provide apt-fast with the necessary options to skip the proxies. As the command line parameters are forwarded to apt*, you should be able to use something like

    alias apt-fast='apt-fast -o Acquire::http::Proxy= -o Acquire::https::Proxy= update'

**Comment by Lasall** [comment]
I think this issue is resolved. If there are any open points or questions, please feel free to reopen.

**Comment by eriabfour** [comment]
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
