### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by mvxt** [ilikenwf/apt-fast#180]
Hi, are there publicly available benchmarking results comparing the performance of just plain `apt-get` vs. with `apt-fast`? Primarily asking out of curiosity

**Comment by guekho64** [comment]
Luckily for you, there are some.

Here: [https://github.com/ilikenwf/apt-fast/issues/163](https://github.com/ilikenwf/apt-fast/issues/163)

In a nutshell, _apt-fast_ tends to improve bad/medium quality connections and, ironically, it can slow down good/excellent internet connections, based on the above issue, which contains a lot more info you might be interested in.

**Comment by mvxt** [comment]
Awesome, thank you for linking that!

**Comment by eriabfour** [comment]
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
