### ISSUE TITLE
Request to tag a new version

### ISSUE THREAD

**Issue by shivammathur** [ilikenwf/apt-fast#181]
@ilikenwf @Lasall
Please tag a new release after exit code fixes and update the same on Ubuntu PPA.

**Comment by Lasall** [comment]
New version 1.9.10 is tagged and PPA updated. Bionic is added as supported version. Thank you for the nudge :+1:

**Comment by eriabfour** [comment]
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
