### ISSUE TITLE
[FEATURED] Progress Bar

### ISSUE THREAD

**Issue by Mr-Vladi** [ilikenwf/apt-fast#182]
Hi, I've been using apt-fast for quite some time and yet I've noticed that it doesn't have a progress bar like the original apt-get, I don't know if it's already included or if it needs to be activated. But it would be fine, it's a very good script and it really does enable fast downloads.

**Comment by gothicVI** [comment]
This won't work as the installation is done by `dpkg` and not by `apt(-get)`.

**Comment by eriabfour** [comment]
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
