### ISSUE TITLE
FIX #minor aptitude show should not sudo

### ISSUE THREAD

**Issue by allanlaal** [ilikenwf/apt-fast#196]
`apt-fast default = aptitude`

currently `apt-fast show packagename` asks for a password
sudo is not needed for this subcommand, its a readonly thing :)

**Comment by Lasall** [comment]
Thank you for the report. This also applies to "apt" package manager.

**Comment by eriabfour** [comment]
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
