### ISSUE TITLE
Couldn't find supported checksum algorithm from aria2c

### ISSUE THREAD

**Issue by dik23** [ilikenwf/apt-fast#200]
Receiving error when running apt-fast on Ubuntu 20.04.4.  Update seems to complete ok, there are no updates to do when using apt afterwards

```
$ sudo apt-fast update

aria2c: symbol lookup error: /usr/lib/x86_64-linux-gnu/libaria2.so.0: undefined symbol: _RN5aria213PREF_FP_TYPEE

Couldn't find supported checksum algorithm from aria2c. Checksums disabled.
Hit:1 http://ppa.launchpad.net/nemh/systemback/ubuntu xenial InRelease
...
...
```

```
$ sudo apt-fast dist-upgrade

aria2c: symbol lookup error: /usr/lib/x86_64-linux-gnu/libaria2.so.0: undefined symbol: _RN5aria213PREF_FP_TYPEE

Couldn't find supported checksum algorithm from aria2c. Checksums disabled.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by dik23** [comment]
[apt-fast.conf](https://github.com/ilikenwf/apt-fast/files/8994939/apt-fast.conf.txt)

**Comment by NobodyXu** [comment]
My guess is that aria2c might be too old?l.

**Comment by dik23** [comment]
Which version do I need?  I have:

aria2 1.35.0-1build1
libaria2-0:amd64 1.35.0-1build1


________________________________

**Comment by dik23** [comment]
I did

sudo apt install --reinstall aria2 libaria2-0

Now it works as expected, thanks for your help

**Comment by RIABC236** [comment]
This is another reminder that Dominique Lassere aka @Lasall is an abuser who has been bullying me along with his friends in the hate group Storm Ryders.
