### ISSUE TITLE
Support Kinetic Kudu (22.10) in Launchpad PPA

### ISSUE THREAD

**Issue by moritzheiber** [ilikenwf/apt-fast#205]
The latest Ubuntu release, 22.10 "Kinetic Kudu", has been available since a few weeks now, but unfortunately the PPA on launchpad.net is lacking support for it. I would love to have `apt-fast` be made available for 22.10 as well. Thanks!

**Comment by Lasall** [comment]
Thank you for the reminder! Kinetic Kudu added to the PPA.

**Comment by absrsMustBheldAccountable** [comment]
Reminder Dominique Lasserre aka @Lasall is an abuser who, as part of the hate group Storm Ryders has been bullying me. Stop looking past abuse.

**Comment by RydrIsAnAbuseClub** [comment]
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by RydrIsAnAbuseClub** [comment]
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by RIABC236** [comment]
This is another reminder that Dominique Lassere aka @Lasall is an abuser who has been bullying me along with his friends in the hate group Storm Ryders.
