### ISSUE TITLE
weak algorithm warning

### ISSUE THREAD

**Issue by priyaranjankumar** [ilikenwf/apt-fast#238]
While running apt-get update, It showing below warning message about the repo

W: https://ppa.launchpadcontent.net/apt-fast/stable/ubuntu/dists/noble/InRelease: Signature by key A2166B8DE8BDC3367D1901C11EE2FF37CA8DA16B uses weak algorithm (rsa1024)

**Comment by ethauvin** [comment]
Same here using Ubuntu 24.04.

**Comment by Lasall** [comment]
The PPA signing algorithm is managed from the Launchpad platform itself. See also https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854
Hopefully they will change they key soon, so you don´t get that warning anymore.

**Comment by Lasall** [comment]
Thank you for your report. The signing key was updated, README is updated as well.
