### ISSUE TITLE
regular expressions is broken

### ISSUE THREAD

**Issue by yurikoles** [ilikenwf/apt-fast#24]
http://pastebin.com/ePhPiRSH

**Comment by Lasall** [comment]
This issue got fixed with e471a772 . Thank you to Niels!

**Comment by RydrIsAnAbuseClub** [comment]
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by noexcuse4u** [comment]
Reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years together with his buddies in the hate group Storm Ryders and is now trying to cover that up.
