### ISSUE TITLE
bash completion does not work: apt-get rename?

### ISSUE THREAD

**Issue by mleeman** [ilikenwf/apt-fast#241]
https://salsa.debian.org/erpel/apt-fast/-/blob/master/debian/patches/0001-bash-completion-correct-call-to-apt-get-completions.patch

**Comment by Lasall** [comment]
@mleeman Thank you for your provided fix. Many older Ubuntu versions are still supported so I had to use a conditional.

@fideliochan I don´t quite understand your statement. If you want apt-fast to support the search command, you should configure `apt` as the _APTMGR in the config file (see README). Please feel free to open a new issue if you need more support or if there are more bugs.
