### ISSUE TITLE
Using PPA repository for Ubuntu Jammy (22.04.x) causes installation on Debian Bullseye (11.x) to fail

### ISSUE THREAD

**Issue by win98se** [ilikenwf/apt-fast#242]
> ```
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following additional packages will be installed:
>   aria2 libaria2-0 libc-ares2
> Suggested packages:
>   aptitude zsh fish
> The following NEW packages will be installed:
>   apt-fast aria2 libaria2-0 libc-ares2
> 0 upgraded, 4 newly installed, 0 to remove and 140 not upgraded.
> Need to get 1,734 kB of archives.
> After this operation, 6,383 kB of additional disk space will be used.
> Do you want to continue? [Y/n] 
> Get:1 http://deb.debian.org/debian bullseye/main i386 libc-ares2 i386 1.17.1-1+deb11u3 [106 kB]
> Get:2 http://deb.debian.org/debian bullseye/main i386 libaria2-0 i386 1.35.0-3 [1,227 kB]
> Get:3 http://ppa.launchpad.net/apt-fast/stable/ubuntu jammy/main i386 apt-fast all 1.11.0-1~ubuntu22.04.1 [38.3 kB]
> Get:4 http://deb.debian.org/debian bullseye/main i386 aria2 i386 1.35.0-3 [363 kB]
> Fetched 1,734 kB in 2s (720 kB/s)
> Preconfiguring packages ...
> Selecting previously unselected package libc-ares2:i386.
> (Reading database ... 179749 files and directories currently installed.)
> Preparing to unpack .../libc-ares2_1.17.1-1+deb11u3_i386.deb ...
> Unpacking libc-ares2:i386 (1.17.1-1+deb11u3) ...
> Selecting previously unselected package libaria2-0:i386.
> Preparing to unpack .../libaria2-0_1.35.0-3_i386.deb ...
> Unpacking libaria2-0:i386 (1.35.0-3) ...
> Selecting previously unselected package aria2.
> Preparing to unpack .../aria2_1.35.0-3_i386.deb ...
> Unpacking aria2 (1.35.0-3) ...
> dpkg-deb: error: archive '/var/cache/apt/archives/apt-fast_1.11.0-1~ubuntu22.04.1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
> dpkg: error processing archive /var/cache/apt/archives/apt-fast_1.11.0-1~ubuntu22.04.1_all.deb (--unpack):
>  dpkg-deb --control subprocess returned error exit status 2
> Errors were encountered while processing:
>  /var/cache/apt/archives/apt-fast_1.11.0-1~ubuntu22.04.1_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```
Changing to using PPA repository for Ubuntu Focal (20.04.x) works fine -
> ```
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Suggested packages:
>   aptitude zsh fish
> The following NEW packages will be installed:
>   apt-fast
> 0 upgraded, 1 newly installed, 0 to remove and 140 not upgraded.
> 3 not fully installed or removed.
> Need to get 36.7 kB of archives.
> After this operation, 131 kB of additional disk space will be used.
> Get:1 http://ppa.launchpad.net/apt-fast/stable/ubuntu focal/main i386 apt-fast all 1.11.0-1~ubuntu20.04.1 [36.7 kB]
> Fetched 36.7 kB in 1s (37.7 kB/s) 
> Preconfiguring packages ...
> Selecting previously unselected package apt-fast.
> (Reading database ... 179825 files and directories currently installed.)
> Preparing to unpack .../apt-fast_1.11.0-1~ubuntu20.04.1_all.deb ...
> Unpacking apt-fast (1.11.0-1~ubuntu20.04.1) ...
> Setting up libc-ares2:i386 (1.17.1-1+deb11u3) ...
> Setting up libaria2-0:i386 (1.35.0-3) ...
> Setting up aria2 (1.35.0-3) ...
> Setting up apt-fast (1.11.0-1~ubuntu20.04.1) ...
> Processing triggers for man-db (2.9.4-2) ...
> Processing triggers for libc-bin (2.31-13+deb11u7) ...
> ```

**Comment by Lasall** [comment]
Thank you! I updated the readme.
