### ISSUE TITLE
Shell completions suggestion: Automatically update alias when using another package manage that is not `apt-get`

### ISSUE THREAD

**Issue by hueychen27** [ilikenwf/apt-fast#244]
I am using `apt` as the package manager to use for `apt-fast`, but the completions list was wrong. I had to go manually change the completions file to this:
```
#compdef apt-fast
compdef _apt apt-fast=apt
```
instead of `apt-get` for the last word after the equals sign. I think it would be a good idea to automatically update the file when using a different default package manager than `apt-get`.

**Comment by Lasall** [comment]
Thank you very much for this feature request. Can you try with the current master?

**Comment by hueychen27** [comment]
Alright. Thank you for fixing this fast.
