### ISSUE TITLE
All that is shown is apt

### ISSUE THREAD

**Issue by dougg0k** [ilikenwf/apt-fast#246]
Hi,

Maybe I misunderstood how it works.

But unless I intentionally use `apt-fast install` not even aliases are able to reach `apt-fast`, it's like it doesn't exist.

```
nu ❯ apt --version
apt 2.4.12 (amd64)

nu ❯ apt-fast --version
apt 2.4.12 (amd64)

nu ❯ apt-get --version
apt 2.4.12 (amd64)
```

```
nu ❯ cat /etc/apt-fast.conf
───────┬────────────────────────────
       │ File: /etc/apt-fast.conf
───────┼────────────────────────────
   1   │ _APTMGR=apt
   2   │ _MAXCONPERSRV=16
   3   │ DOWNLOADBEFORE=true
   4   │ _MAXNUM=8
───────┴─────────────────────────────
```

```
alias apt = apt-fast
alias apt-get = apt-fast
```

Any reason why?

**Comment by Lasall** [comment]
Hello dougg0k! apt-fast is just a shell wrapper around the real package managers' cli applications. And only certain commands are wrapped (like install, upgrade, download, etc.). For all other options and commands (like --version) they just get passed to the underlying package manager.

**Comment by dougg0k** [comment]
I see, however, if i do apt install even with alias, ir does not trigger apt-fast.

Any idea why?

**Comment by Lasall** [comment]
Probably you just have to set _APTMGR in the config file /etc/apt-fast.conf to a full path, e.g., /usr/bin/apt

**Comment by dougg0k** [comment]
It didnt work.

I was testing out. Weird results.

Normally when I run a `apt-fast install` briefly shows a `Working... this may take a while.` colored and vanishes.

When trying the same with `apt` it doesnt, as if it was not there, not even the ms delay that happens when it appears.

Now I tried running the command like this, and

```
nu ✗ sudo (apt install apt-fast)
sudo: [apt-fast 19:08:09]
[apt-fast 19:08:09]Working... this may take a while.
Reading package lists...
Building dependency tree...
Reading state information...
apt-fast is already the newest version (1.11.1-1~ubuntu22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.: command not found

nu ✗ sudo (apt-fast install apt-fast)
sudo: [apt-fast 19:12:06]
[apt-fast 19:12:06]Working... this may take a while.
Reading package lists...
Building dependency tree...
Reading state information...
apt-fast is already the newest version (1.11.1-1~ubuntu22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.: command not found
```

It is there. But no delay. But I dont see the difference from normal.

**Comment by Lasall** [comment]
What shell are you using?

**Comment by dougg0k** [comment]
nushell, but I tried on bash, and result was the same.

**Comment by Lasall** [comment]
I cannot reproduce the described behavior on neither nushell nor bash. Could you please try the following in bash:
```
cat /etc/apt-fast.conf
export _APTMGR=apt-get
alias apt-fast=apt-get
set -x
apt-get install apt-fast
```

**Comment by dougg0k** [comment]
I just figured out, it was my fault, it was due to sudo.

I never tried without using sudo, as with apt, if you ask for without sudo. It straight gives you an error.

While with apt-fast, it does not.

```
nu ❯ apt install apt-fast
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
                                                                                                                                                                                                                                                                      
~
nu ✗ apt-fast install apt-fast
[sudo] password for user:
```

Thanks for the help anyhow.
