### ISSUE TITLE
Support update command

### ISSUE THREAD

**Issue by Lasall** [ilikenwf/apt-fast#36]
As asked in iloveubuntu blog post [1](http://www.iloveubuntu.net/apt-fast-164-released-fixes-and-proper-configuration-dialog#comment-600215162), there is no support of update command yet.
Usage of `apt-get --print-uris update` works mostly fine but we have to save those files in specific location. They have same names like "Sources.bz2". "Packages.bz2" etc. so we have to rename them. With aria2 this works well with following download list example:

```
http://ftp.debian.org/debian/dists/experimental/main/i18n/Translation-en.bz2
 out=ftp.debian.org_debian_dists_experimental_main_i18n_Translation-en
http://ftp.debian.org/debian/dists/unstable/main/source/Sources.bz2
 out=ftp.debian.org_debian_dists_unstable_main_source_Sources
```

With axel this is not possible (yes we have --output option but only for one single file). Should we drop axel support because it already has a disadvantage: no download resuming

I'm nearly done with update command integration but at the moment it would break axel compatibility. But perhaps we could grep _DOWNLOADER for axel or aria and (if necessary) fallback to `apt-get update` without download acceleration.
I like the last idea to determine it on the fly.

@ilikenwf and others: What are your opinions?

**Comment by jayenashar** [comment]
>     1. Even package lists wich are uptodate are downloaded. Atm I have no idea how to check that because we even don't know the exact URL of package lists.

anyone know if this has changed in the last 5 years?  i did a quick google search but it seems there's no way to get the apt cli to list the urls it will try.  it might be dynamic.  has anyone looked at libapt and would integrating with that be considered?

**Comment by Lasall** [comment]
Using libapt is the proper way to achieve this, among speeding up apt-fast computations of uris to download. However this would require a rewrite of the "simple" apt-fast Shell-Skript (in Python or C++).

**Comment by jayenashar** [comment]
could someone write a wrapper for just the URLs of package lists, and then the apt-fast script could use the wrapper?  kind of like a plugin for apt-fast?  would that still require a rewrite of the script?

**Comment by Lasall** [comment]
Using a "plugin" that gets the uris "natively" is possible. It's probably also possible to write an "apt-fast/aria2" plugin for apt.

**Comment by thebestestseb** [comment]
Reminder that Dominique Lassere aka @Lasall is an abuser who along with his buddies in the hate group Storm Riders has been bullying me for years and is now trying to cover that up.
