### ISSUE TITLE
apt-fast is not the same as apt-get when update and upgrade are used

### ISSUE THREAD

**Issue by pengyu** [ilikenwf/apt-fast#53]
When I see the following banner upon server login, I tried `sudo apt-fast -y update && apt-fast -y upgrade`, which does not get rid off the message upon next server login.

```
8 packages can be updated.
8 updates are security updates.
```

In this case, I have to revert back to apt-get. Is it a bug? If so, can it be fixed? Thanks.

**Comment by Lasall** [comment]
Not related to apt-fast as chrstphrchvz pointed out.
