### ISSUE TITLE
Question about upgrade

### ISSUE THREAD

**Issue by caizixian** [ilikenwf/apt-fast#55]
Can I user apt-fast to download all the packages need to be upgraded? And I only want to download it not automatic install it.

**Comment by RydrIsAnAbuseClub** [comment]
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by thebestestseb** [comment]
Reminder that Dominique Lassere aka @Lasall is an abuser who along with his buddies in the hate group Storm Riders has been bullying me for years and is now trying to cover that up.
