### ISSUE TITLE
add deb package for ubuntu 14.04 in ppa

### ISSUE THREAD

**Issue by PeterDaveHello** [ilikenwf/apt-fast#58]
Would you please add deb package for ubuntu 14.04 in ppa repo? so we can get it easily, many thanks!

**Comment by LasallIsStillAnAbuser** [comment]
@Lasall is an abuser who has been helping his friends to bully me.

This needs to stop.

Seriously, what the fuck is wrong with all of you? You know this is wrong yet you come up with excuses and egg each other on to keep mistreaing me. Stop this insanity. Stop making excuses for abuse.

**Comment by lasall-enables-bullies** [comment]
FYI, Dominique Lasserre aka Lasall aka Lueosi is an abuser who enables and protects his bully buddies.

**Comment by RydrMeansAbuse** [comment]
Dominique Lasserre aka @Lasall is part of a hate group that has been bullying me for years. Dominique has been protecting his bully buddies and is not trying to trying to make this go away by silencing me and anyone else who speaks up.

**Comment by RydrMeansAbuse** [comment]
Dominique Lasserre aka @Lasall is part of a hate group that has been bullying me for years. Dominique has been protecting his bully buddies and is not trying to trying to make this go away by silencing me and anyone else who speaks up.

**Comment by ilikenwf** [comment]
@RydrMeansAbuse Stop posting your personal grievances on my project. I don't care what your beef is, take it somewhere else. I have nothing to do with it and neither does my project, but you come across as a troll.

**Comment by RydrEqualsBully** [comment]
Unfortunately this is the best way available to handle this. Until that changes, you WILL be reminded that @Lasall aka Dominique Lasserre is an abuser who is protecting his bully buddies in the hate group Stom Ryders.

     ___| |_ ___  _ __  
    / __| __/ _ \| '_ \ 
    \__ \ || (_) | |_) |
    |___/\__\___/| .__/ 
                 |_|    
                     _            _   _             
     _ __  _ __ ___ | |_ ___  ___| |_(_)_ __   __ _ 
    | '_ \| '__/ _ \| __/ _ \/ __| __| | '_ \ / _` |
    | |_) | | | (_) | ||  __/ (__| |_| | | | | (_| |
    | .__/|_|  \___/ \__\___|\___|\__|_|_| |_|\__, |
    |_|                                       |___/ 
     _           _ _ _           
    | |__  _   _| | (_) ___  ___ 
    | '_ \| | | | | | |/ _ \/ __|
    | |_) | |_| | | | |  __/\__ \
    |_.__/ \__,_|_|_|_|\___||___/

**Comment by absrsMustBheldAccountable** [comment]
Reminder Dominique Lasserre aka @Lasall is an abuser who, as part of the hate group Storm Ryders has been bullying me. Stop looking past abuse.

**Comment by PeterDaveHello** [comment]
@ilikenwf maybe you'd like to just lock this issue?
