### ISSUE TITLE
Support for apt-cacher-ng

### ISSUE THREAD

**Issue by drsood** [ilikenwf/apt-fast#77]
How can I use apt-fast with apt-cacher-ng?

**Comment by voltagex** [comment]
It should respect the `http_proxy` environment variable, or set the `sources.list` entry to `http://apt-cacher-ng-host/debian ...`

**Comment by lordloh** [comment]
I am using 

`_DOWNLOADER='aria2c -c -j ${_MAXNUM} -x ${_MAXNUM} -s ${_MAXNUM} --min-split-size=${_MINSPLITSZ} --http-proxy=http://apt-cacher-ng_host:3142 -i ${DLLIST} --connect-timeout=600 --timeout=600 -m0'`

**Comment by Lasall** [comment]
It looks like this issue is resolved with lordloh's example. Please reopen if not working.
