### ISSUE TITLE
Proper sources.list update

### ISSUE THREAD

**Issue by A-Shahbazi** [ilikenwf/apt-fast#78]
When I change the server from which I want to get the packages without reloading package lists ( Software & Updates > Ubuntu Software Tab > Download from: ) and then I run apt-get update the /etc/apt/sources.list file is updated correctly but when I run apt-fast update there are still some lines indicating previous server.
let's say if the old server is http://us.archive.ubuntu.com/ubuntu/ and the newly selected one is http://archive.ubuntu.totaal.net/ there are still deb http://us.archive.ubuntu.com/ubuntu/... lines in sources.list

**Comment by Lasall** [comment]
Thank you for reporting this issue. apt-fast passes the update option to the selected package manager tool (like apt-get, aptitude, apt) without changes. Just like apt-get it will never change the sources.list. This is exclusive to the Software Center and other high level applications.

In case you can track down this issue being related to apt-fast please reopen.
