### ISSUE TITLE
No tag for 1.8.x

### ISSUE THREAD

**Issue by thedrow** [ilikenwf/apt-fast#80]
Can you please tag your releases?

**Comment by PeterDaveHello** [comment]
+1
ping @ilikenwf

**Comment by ilikenwf** [comment]
Just tagged the current version as 1.8, but I'm not sure if it is stable as I haven't really been  using the tool lately.

**Comment by thedrow** [comment]
It works. There are some bugs but it does work.

**Comment by varhub** [comment]
@thedrow @ilikenwf , sorry for resurrect closed issue.

I saw [official ppa](https://launchpad.net/~saiarcot895/+archive/ubuntu/myppa/+packages) and it seems to have a 1.8.3 version. Perhaps follow same number will simplify porting from *apt-get install* to *git* and reverse.
`git tag 1.8.3 af73a17`
