### ISSUE TITLE
Unable to autoinstall apt-fast (without interaction)

### ISSUE THREAD

**Issue by heniokalinowski** [ilikenwf/apt-fast#85]
Hi,
during instalation apt-fast asks for:
- application manager (apt-get/aptitude)
- number of connections
- shall it skip confirmation

It prevents apt-fast to be installed in non-interactive way.
I think, that it should install with defaults, and allow to change it later ("convention over configuration").

I propose:
application manager = aptitude installed ? aptitude : apt-get
connections = 5 (that's Your proposal) or 10 (my personal choice - helps with many small files)
skip = true

If You are unable to do so, for whatever reason, then maybe You are able to provide names and values for debconf-utils.
I have unsuccessfully tried:

echo 'apt-fast apt-fast/_APTMGR string aptitude' | sudo debconf-set-selections
echo 'apt-fast apt-fast/maxdownloads string  10' | sudo debconf-set-selections
echo 'apt-fast apt-fast/DOWNLOADBEFORE boolean true' | sudo debconf-set-selections

Which hangs whole installation with holding one CPU core at 100%...

P.S. 
Why isn't apt-fast in default repository of Debian/Ubuntu/Linux Mint?

**Comment by Thell** [comment]
Did you set the frontend to noninteractive?
````bash
echo "debconf debconf/frontend select Noninteractive" | debconf-set-selections;
````

and use `dflag` instead of DOWNLOADBEFORE?

````bash
echo "apt-fast apt-fast/maxdownloads string 10" | debconf-set-selections; \
echo "apt-fast apt-fast/dlflag boolean true" | debconf-set-selections; \
apt-get -qq install apt-fast
````

Also, the conf doesn't seem to stick for the other options _I've_ tried so sed my be the answer for you on the `_APTMGR` part, for instance I use the following for the download command.

````
sed -i'' "/^_DOWNLOADER=/ s/-m0/-m0 --console-log-level=error --show-console-readout=false/" /etc/apt-fast.conf; \
````

**Comment by dsifford** [comment]
@Thell 's answer above works. 

But so does this `DEBIAN_FRONTEND=noninteractive apt-get install -y apt-fast`

**Comment by bartekbrak** [comment]
@dsifford 
> DEBIAN_FRONTEND=noninteractive apt-get install -y apt-fast

does not work, the installer still asks questions; can you try again after purging the package?
```
sudo apt-get purge apt-fast; DEBIAN_FRONTEND=noninteractive apt-get install -y apt-fast 
```

@Thell's answer indeed works, still this behaviour is unfortunate, took me a while to solve, time wasted for no reason.

**Comment by dsifford** [comment]
@bartekbrak `sudo apt-get purge` will not work because you are both a) using sudo (non-root) and b) not giving purge the `-y` flag

**Comment by ctindel** [comment]
I did this and it worked on Ubuntu 16.04:

```
echo debconf apt-fast/maxdownloads string 16 | sudo debconf-set-selections
echo debconf apt-fast/dlflag boolean true | sudo debconf-set-selections
echo debconf apt-fast/aptmanager string apt-get | sudo debconf-set-selections
sudo apt-get install apt-fast
```

**Comment by Lasall** [comment]
Thank you everyone for the comments, I updated the README with the required instructions.
