### ISSUE TITLE
does not work on ubuntu 15.10

### ISSUE THREAD

**Issue by ghost** [ilikenwf/apt-fast#89]
Failed to fetch http://ppa.launchpad.net/saiarcot895/myppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

**Comment by mmtxr** [comment]
Probably this repository is offline by now. Here Apt-fast is working well. Just tested

**Comment by Kwaadpepper** [comment]
It is not (yet hopefuly) packaged for wily, but manual install is ok

**Comment by saiarcot895** [comment]
Now packaged for wily, and should be available in an hour or two.

**Comment by Kwaadpepper** [comment]
Thanks for that :)

**Comment by adamcavendish** [comment]
@srpelissiermythx You should look at the https://launchpad.net/~saiarcot895/+archive/ubuntu/myppa link and view the `Published in` information to see whether your distribution version is supported or not.

Anyway, now I find out 15.10 is supported and you'll be good.

**Comment by PeterDaveHello** [comment]
Another problem is that there are not only apt-fast in that ppa, may cause something apt-fast users do not want, so I wrote a makefile to help install easily without ppa, see #93.

**Comment by PeterDaveHello** [comment]
@ilikenwf maybe you can close this now, the issuer became Ghost account.
