### ISSUE TITLE
Does this work with my fabric script?

### ISSUE THREAD

**Issue by rlam3** [ilikenwf/apt-fast#90]
Does this work with my fabric script?

Installed apt-fast and did an alias apt-get="apt-fast" in my bash_profile
Looks about the same speed for me. Am I doing something wrong?

Or does it just not play well with fabric script?

**Comment by saiarcot895** [comment]
If you're prefixing the command with `sudo`, then it's not going to see the alias in your `bash_profile`, and is going to execute the binary instead.

Having `alias apt-get="sudo apt-fast"` might work (at least to some extent).

**Comment by Lasall** [comment]
This doesn't look like an issue to me. Shell aliases should not affect shell scripts and your MAXNUM was maybe too low and or the servers or your connection was already at maximum bandwidth.
Please reopen if I misunderstood.
